#!/bin/bash

#
#  sonos-group-manager - see sonos-group-manager.py for details.
#

#
#  The MIT License (MIT)
#  
#  Copyright (c) 2015 Nnamdi Onyeyiri
#  
#  Permission is hereby granted, free of charge, to any person obtaining a copy of this software 
#  and associated documentation files (the "Software"), to deal in the Software without 
#  restriction, including without limitation the rights to use, copy, modify, merge, publish, 
#  distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the 
#  Software is furnished to do so, subject to the following conditions:
#  
#  The above copyright notice and this permission notice shall be included in all copies or 
#  substantial portions of the Software.
#  
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
#  BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
#  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
#  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#  

#  Set the number of seconds to wait after all zones stop playing
#  before reverting to the default topology.  The default is 5.
#
#  export SONOS_GM_REVERT_DELAY=5

#  Turn on/off automatic rejoining of Playbars current playing TV
#  to their default group, when the default group starts playing.
#  The default is 1.
#
#  export SONOS_GM_PLAYBAR_REJOIN_GROUP_ON_PLAY=1

#  Turn on/off logging of messages/actions to stdout.  The default
#  is 0.
#
#  export SONOS_GM_ENABLE_LOGGING=0

#  The path to store the PID file. The default is /tmp.
#
#  export SONOS_GM_PID_FILE_PATH=/tmp

nohup ./sonos-group-manager.py > /tmp/sonos-group-manager.log 2>&1 &

